### ISSUE TITLE
I couldn't configure the number.

### ISSUE THREAD

**Issue by iagosauer** [rohit-chouhan/whatsapp#10]
To configure the number, it asks for an ID and a TOKEN, but I have no idea how I get this information on my WhatsApp, I thought I could generate a QRCODE to connect the device.
Developers could specify these things better.

**Comment by rohit-chouhan** [comment]
You have to create APP from developers.facebook.com, there you will find token and id.
follow this blog for reference :- https://developers.facebook.com/docs/whatsapp/
