### ISSUE TITLE
 Update for messagesTemplate

### ISSUE THREAD

**Issue by Roberto9991** [rohit-chouhan/whatsapp#11]
Hello, through the screens you can use variables.
the change should be the following:
`/// Send the template to the client.
  /// [to] is the phone number with country code but without the plus (+) sign.
  /// [templateName] is the template name.
  /// [message] is the message to be sent.
  Future messagesTemplate({int? to, String? templateName, String? message}) async {
    var url = 'https://graph.facebook.com/v15.0/$_fromNumberId/messages';
    Uri uri = Uri.parse(url);

    Map data = {
      "messaging_product": "whatsapp",
      "to": to,
      "type": "template",
      "template": {
        "name": templateName,
        "language": {"code": "es_AR"},
        "components": [
        {
            "type": "body",
            "parameters": [{
                    "type": "text",
                    "text": message
                }]
        }
      ]
      }
    };
`
my english is not very good i hope you understand

**Comment by iampopal** [comment]
We also need the variables and language flexibility feature as parameters

**Comment by rohit-chouhan** [comment]
Sorry for the delay, we have released new version. now you can have language flexibility. please find more details here : https://whatsapp-flutter.github.io/docs/methods/messages/send-a-template

Please let me know, if you need any support.
