### ISSUE TITLE
problem sending audio

### ISSUE THREAD

**Issue by eduardohr-muniz** [rohit-chouhan/whatsapp#12]
I need to send an audio it's giving 200 but the audio doesn't send it, I'm using this package https://pub.dev/packages/record to record the audio and I sent it in all codecs none of it worked, could you give me a light?

**Comment by rohit-chouhan** [comment]
Sorry for the delay, we have released new version. please find more details here : https://whatsapp-flutter.github.io/docs/methods/media/upload-media

Please let me know, if you need any support.
