### ISSUE TITLE
Problem messagesText

### ISSUE THREAD

**Issue by filipedrisostes** [rohit-chouhan/whatsapp#13]
Hi

I'm using the example app and the function messagesText doesn't work. It return correctly, but the message doesn't appear in my whatsapp. What could be happening?

Follow the print

![image](https://github.com/rohit-chouhan/whatsapp/assets/20359864/cf3dfb05-7c4d-417b-8f6a-b7a63f320f21)

**Comment by ibrahimgamalf** [comment]
Hi filip, did you figure this out? Did you solve this issue or find an alternative solution, because I want to send messages through whatsapp but I didn't figure out the solution till now?

**Comment by Elmarcinho** [comment]
Hi filip, did you figure this out? Did you solve this issue or find an alternative solution??

**Comment by rohit-chouhan** [comment]
Sorry for the delay, we have released new version hope you issue will be fixed.

Please let me know, if you need any support.
