### ISSUE TITLE
Send to whatsapp group.

### ISSUE THREAD

**Issue by AbodiSadiqGitHub** [rohit-chouhan/whatsapp#3]
I want to send message to whatsapp group, please.
How can I do that?

**Comment by rohit-chouhan** [comment]
use messagesTemplate() method, and pass group_id in **to** property.
ex. 
`whatsapp.messagesTemplate(
	to: 10000000034254, //group id
	templateName: "hello_world" //template name
);`

**Comment by AbodiSadiqGitHub** [comment]
> use messagesTemplate() method, and pass group_id in **to** property. ex. `whatsapp.messagesTemplate( to: 10000000034254, //group id templateName: "hello_world" //template name );`
can you give me an example,
'https://chat.whatsapp.com/JiATE6rTObME5UXacTIfcw' this is a group link,
how can i do?
and what is template name in this case?

thanks Aloot!
