### ISSUE TITLE
Duda sobre envio de mensajes "Send text message"

### ISSUE THREAD

**Issue by Albertiko74** [rohit-chouhan/whatsapp#6]
En la documentación para enviar un mensaje aplicando whatsapp 2.0.0 aparece como:

whatsapp.messagesTemplate(
	to: 910000000000,
	message: "Hey, Flutter, follow me on https://example.com",
	previewUrl: true
);
Esto es correcto?

Cuando utilizo ya configurado en flutter "whatsapp 2.0.0"  si funciona con messagesTemplate y recibo en mi celular el mensaje del template de developer facebook, pero cuando lo intento con:

whatsapp.messagesText(
   	          to: 910000000000,
	message: "Hey, Flutter, follow me on https://example.com",
     previewUrl: true
);

No recibo el mensaje en mi celular, aplique flutter logs y aparece lo siguiente:

![evidencia envio WHATSAPP](https://user-images.githubusercontent.com/116118039/196536330-d09792cd-4ef7-4570-a5ce-f7c55640f839.jpg)

**Comment by rohit-chouhan** [comment]
if logs is return as 
```dart
'{ "messaging_product": "whatsapp", "to": "15555555555", "type": "template", "template": { "name": "hello_world", "language": { "code": "en_US" } } }'
```

that's mean, its correct
