### ISSUE TITLE
Add "components" field for making the templates more useful in production environments 

### ISSUE THREAD

**Issue by nabilpatel4012** [rohit-chouhan/whatsapp#7]
## Adding Components field will make the "messagesTemplate" function more useful.
I have modified the definition of the "messagesTemplate" a bit for my use case and realised that It will be useful for many people out there for integrating WhatsApp api more efficiently and easily.
![image](https://user-images.githubusercontent.com/80565100/197877320-d2ad536e-1d2a-4789-8497-e83ab4bcef60.png)
Here you can see the modified changes I have made in this function definition.
You can add this as a seperate feature or extend the "messageTemplate" by adding another fields.
I am always ready to contribute and help you at any point.

**Comment by rohit-chouhan** [comment]
Feel free to contribute we will review.
