### ISSUE TITLE
Problems using: Send text message

### ISSUE THREAD

**Issue by luciano-da-cruz-jr** [rohit-chouhan/whatsapp#9]
send text message
💬 Send the text message to the customer.

to- the phone number with the country code, but without the plus sign (+).
message- the message to be sent.
previewUrl- is used to preview the URL in the chat window.
```
whatsapp.messagesTemplate(
to: 910000000000,
message: "Hey Flutter, follow me on https://example.com",
previewUrl: true
);
```
The message does not send.

Actually, it's correct to use:

```
whatsapp.messagesText(
to: 910000000000,
message: "Hey Flutter, follow me on https://example.com",
previewUrl: true
);
```
But I still can't send it!

My friends could help me please, thanks in advance!

![image](https://user-images.githubusercontent.com/104800760/214361659-71b552f6-22b0-4edc-a50d-1f9d963697a8.png)

**Comment by rohit-chouhan** [comment]
function always return a status, please check what message you are getting and share screenshot. Thanks,
